version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: kirke
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: openjdk:17-jdk
    container_name: app
    ports:
      - "8012:8012"
    depends_on:
      - redis
      - postgres
      - mongodb
    networks:
      - mynetwork
    volumes:
      - .:/app
    command: ["bash"]

networks:
  mynetwork:
    driver: bridge
